### ISSUE TITLE
Pokemon Family Colors

### ISSUE THREAD

**Issue by sw45859** [OrangeeWeb/Pokemon#1]
i have done what i had, this is based on the family of the pokemon, anything that doesn't have a family name is likely a family that doesn't actually exist.

$CandyColors = [
            1 => ['family_name' => 'Bulbasaur', 'primary' => '36c7a5', 'secondary' => 'a1fb82'],
            2 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            3 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            4 => ['family_name' => 'Charmander', 'primary' => 'f2942f', 'secondary' => 'ffe699'],
            5 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            6 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            7 => ['family_name' => 'Squirtle', 'primary' => 'e4e16c', 'secondary' => 'b4d68f'],
            8 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            9 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            10 => ['family_name' => 'Caterpie', 'primary' => 'a9cf8a', 'secondary' => 'ffe3b2'],
            11 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            12 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            13 => ['family_name' => 'Weedle', 'primary' => 'ebc086', 'secondary' => 'db76ad'],
            14 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            15 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            16 => ['family_name' => 'Pidgey', 'primary' => 'ece3ba', 'secondary' => 'd29d65'],
            17 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            18 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            19 => ['family_name' => 'Rattata', 'primary' => 'ad8cbc', 'secondary' => 'dad7be'],
            20 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            21 => ['family_name' => 'Spearow', 'primary' => 'eaba9f', 'secondary' => 'ff5c6b'],
            22 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            23 => ['family_name' => 'Ekans', 'primary' => 'cdaacb', 'secondary' => 'f1e090'],
            24 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            25 => ['family_name' => 'Pikachu', 'primary' => 'f9d769', 'secondary' => 'e1a75c'],
            26 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            27 => ['family_name' => 'Sandshrew', 'primary' => 'e7daa7', 'secondary' => 'cbb57a'],
            28 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            29 => ['family_name' => 'Nidoran Female', 'primary' => 'cadaec', 'secondary' => '9a9ccb'],
            30 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            31 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            32 => ['family_name' => 'Nidoran Male', 'primary' => 'd8a7c8', 'secondary' => 'c0759d'],
            33 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            34 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            35 => ['family_name' => 'Clefairy', 'primary' => 'f6d7d5', 'secondary' => 'f0bfc0'],
            36 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            37 => ['family_name' => 'Vulpix', 'primary' => 'ef8d60', 'secondary' => 'f7d79c'],
            38 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            39 => ['family_name' => 'Jigglypuff', 'primary' => 'f3d3e1', 'secondary' => 'eab8ce'],
            40 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            41 => ['family_name' => 'Zubat', 'primary' => '488bc1', 'secondary' => 'dc8dd7'],
            42 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            43 => ['family_name' => 'Oddish', 'primary' => '7196bf', 'secondary' => '75c06a'],
            44 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            45 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            46 => ['family_name' => 'Paras', 'primary' => 'ee863d', 'secondary' => 'ffd15a'],
            47 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            48 => ['family_name' => 'Venonat', 'primary' => '988ed5', 'secondary' => 'e14476'],
            49 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            50 => ['family_name' => 'Diglett', 'primary' => '', 'secondary' => ''],
            51 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            52 => ['family_name' => 'Meowth', 'primary' => 'ebdfc2', 'secondary' => 'ffe28a'],
            53 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            54 => ['family_name' => 'Psyduck', 'primary' => 'f6c883', 'secondary' => 'f1f0da'],
            55 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            56 => ['family_name' => 'Mankey', 'primary' => 'e9dbcf', 'secondary' => 'c3927f'],
            57 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            58 => ['family_name' => 'Growlithe', 'primary' => 'f2a056', 'secondary' => '3f3d2a'],
            59 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            60 => ['family_name' => 'Poliwag', 'primary' => '89a2cf', 'secondary' => 'ebecf6'],
            61 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            62 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            63 => ['family_name' => 'Abra', 'primary' => 'ebd45e', 'secondary' => '8e7994'],
            64 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            65 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            66 => ['family_name' => 'Machop', 'primary' => '9ec0d5', 'secondary' => 'd8d0c1'],
            67 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            68 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            69 => ['family_name' => 'Bellsprout', 'primary' => 'e6e36d', 'secondary' => 'b4d68f'],
            70 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            71 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            72 => ['family_name' => 'Tentacool', 'primary' => '78bae0', 'secondary' => 'c54c77'],
            73 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            74 => ['family_name' => 'Geodude', 'primary' => 'aea57d', 'secondary' => '766002'],
            75 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            76 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            77 => ['family_name' => 'Ponyta', 'primary' => 'f1ebcb', 'secondary' => 'f59062'],
            78 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            79 => ['family_name' => 'Slowpoke', 'primary' => 'e3a4bd', 'secondary' => 'eee1c7'],
            80 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            81 => ['family_name' => 'Magnemite', 'primary' => 'd5dfe4', 'secondary' => '92b6c6'],
            82 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            83 => ['family_name' => 'Farfetchd', 'primary' => '', 'secondary' => ''],
            84 => ['family_name' => 'Doduo', 'primary' => 'cd9962', 'secondary' => 'af7662'],
            85 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            86 => ['family_name' => 'Seel', 'primary' => '', 'secondary' => ''],
            87 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            88 => ['family_name' => 'Grimer', 'primary' => 'c2a6ca', 'secondary' => '5f5370'],
            89 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            90 => ['family_name' => 'Shellder', 'primary' => 'ae9fc9', 'secondary' => 'e0b5b3'],
            91 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            92 => ['family_name' => 'Gastly', 'primary' => '242223', 'secondary' => '9b7fb7'],
            93 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            94 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            95 => ['family_name' => 'Onix', 'primary' => 'babbbd', 'secondary' => '69696c'],
            96 => ['family_name' => 'Drowzee', 'primary' => 'f8cb57', 'secondary' => 'af7662'],
            97 => ['family_name' => 'Hypno', 'primary' => '', 'secondary' => ''],
            98 => ['family_name' => 'Krabby', 'primary' => '', 'secondary' => ''],
            99 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            100 => ['family_name' => 'Voltorb', 'primary' => 'c0495c', 'secondary' => 'efeff0'],
            101 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            102 => ['family_name' => 'Exeggcute', 'primary' => 'f4dde8', 'secondary' => 'fac9c0'],
            103 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            104 => ['family_name' => 'Cubone', 'primary' => 'd7d8d9', 'secondary' => 'cbb57a'],
            105 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            106 => ['family_name' => 'Hitmonlee', 'primary' => 'c0a18b', 'secondary' => 'eee1c7'],
            107 => ['family_name' => 'Hitmonchan', 'primary' => '', 'secondary' => ''],
            108 => ['family_name' => 'Lickitung', 'primary' => '', 'secondary' => ''],
            109 => ['family_name' => 'Koffing', 'primary' => '8e92b1', 'secondary' => 'dee0bf'],
            110 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            111 => ['family_name' => 'Rhyhorn', 'primary' => 'c1c2c4', 'secondary' => '949ca1'],
            112 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            113 => ['family_name' => 'Chansey', 'primary' => 'e5b2b6', 'secondary' => 'c68d87'],
            114 => ['family_name' => 'Tangela', 'primary' => '686ea0', 'secondary' => 'e46e8c'],
            115 => ['family_name' => 'Kangaskhan', 'primary' => '', 'secondary' => ''],
            116 => ['family_name' => 'Horsea', 'primary' => 'a0d1ec', 'secondary' => 'fcf7d7'],
            117 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            118 => ['family_name' => 'Goldeen', 'primary' => 'eaeaeb', 'secondary' => 'f38469'],
            119 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            120 => ['family_name' => 'Staryu', 'primary' => 'b6976a', 'secondary' => 'f5e688'],
            121 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            122 => ['family_name' => 'Mr Mime', 'primary' => '', 'secondary' => ''],
            123 => ['family_name' => 'Scyther', 'primary' => '95c98a', 'secondary' => 'f6f0cf'],
            124 => ['family_name' => 'Jynx', 'primary' => 'c84753', 'secondary' => '643187'],
            125 => ['family_name' => 'Electabuzz', 'primary' => '', 'secondary' => ''],
            126 => ['family_name' => 'Magmar', 'primary' => 'fad97a', 'secondary' => 'f0664e'],
            127 => ['family_name' => 'Pinsir', 'primary' => 'bfb4ae', 'secondary' => 'cfd4d8'],
            128 => ['family_name' => 'Tauros', 'primary' => 'dda45a', 'secondary' => '887e6f'],
            129 => ['family_name' => 'Magikarp', 'primary' => 'ec7a39', 'secondary' => 'f6f0cf'],
            130 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            131 => ['family_name' => 'Lapras', 'primary' => '', 'secondary' => ''],
            132 => ['family_name' => 'Ditto', 'primary' => '', 'secondary' => ''],
            133 => ['family_name' => 'Eevee', 'primary' => 'cd9962', 'secondary' => '7e5621'],
            134 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            135 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            136 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            137 => ['family_name' => 'Porygon', 'primary' => 'ec777e', 'secondary' => '6bc7c5'],
            138 => ['family_name' => 'Omanyte', 'primary' => 'e0dfcf', 'secondary' => '73cee2'],
            139 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            140 => ['family_name' => 'Kabuto', 'primary' => 'c28523', 'secondary' => '53534a'],
            141 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            142 => ['family_name' => 'Aerodactyl', 'primary' => 'd9bed8', 'secondary' => 'b196c5'],
            143 => ['family_name' => 'Snorlax', 'primary' => '3c6d8b', 'secondary' => 'e6ded0'],
            144 => ['family_name' => 'Articuno', 'primary' => '', 'secondary' => ''],
            145 => ['family_name' => 'Zapdos', 'primary' => '', 'secondary' => ''],
            146 => ['family_name' => 'Moltres', 'primary' => '', 'secondary' => ''],
            147 => ['family_name' => 'Dratini', 'primary' => '92b1d8', 'secondary' => 'efeae6'],
            148 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            149 => ['family_name' => '', 'primary' => '', 'secondary' => ''],
            150 => ['family_name' => 'Mewtwo', 'primary' => '', 'secondary' => ''],
            151 => ['family_name' => 'Mew', 'primary' => '', 'secondary' => ''],
    ];

**Comment by AdressaAgne** [comment]
very nice!
